version: '3.5'

services:
  keycloak:
    container_name: bmi_keycloak
    build:
      context: services/keycloak
    image: bmi/keycloak
    command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-port", "8085"]
    volumes:
      - ./services/keycloak/import:/import
    ports:
      - "8085:8085"
    environment:
      KEYCLOAK_ADMIN: administrator
      KEYCLOAK_ADMIN_PASSWORD: keycloakadmin01!
      KC_HTTP_RELATIVE_PATH: "/auth"
    networks:
      bmi:
        aliases:
          - keycloak.bmi.localhost

networks:
  bmi:
